#pragma once 
// Single file for all #defines

#define WIDTH_FACTOR 16
#define HEIGHT_FACTOR 9
#define TARGET_FRAME_RATE 60
#define SCALE 100

#define TICKS_BUFFER_SIZE 100

#define FAILED_TO_INITIALIZE_SDL -1
#define FAILED_TO_CREATE_WINDOW -2
#define FAILED_TO_CREATE_RENDERER -3
#define FAILED_TO_INITIALIZE_IMAGES -4
#define FAILED_TO_INITIALIZE_FONTS -5